# -*- coding: utf-8 -*-
"""BankRegister.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ikezw-7STH2OAXyb_IQH0Uohai0zqk3t
"""

import random  # ✅ To generate random PIN numbers

# ✅ Menu printed once at the top
print("Welcome to Dhanush's World,\nHelp Desk")
print("\n1. Open a Bank Account")
print("2. Generate Pin Number")
print("3. Change Pin Number")
print("4. Amount Deposit")
print("5. Withdraw Amount")
print("6. Check Balance")
print("7. Exit")

# ✅ Initialize required variables
pin_number = None  # Will store the user's PIN
balance = 0        # Will store the user's balance

while True:
    # ✅ Get user choice inside the loop so menu is interactive
    choice = int(input("\nHow may I help you? Enter the option number (1–7): "))

    # ✅ Open a Bank Account
    if choice == 1:
        name = input("Enter your Name: ")
        age = int(input("Enter your Age: "))
        gender = input("Enter your Gender: ")
        if age < 18:
            print("Minor Account created.")
        else:
            print("Major Account created.")
        print(f"{name} aged {age} has opened an account.")

    # ✅ Generate PIN number
    elif choice == 2:
      generate = input("Enter your name:")
      if name == generate:
        pin_number = random.randint(1000, 9999)  # ✅ Use 4-digit PIN
        print(f"Your generated PIN is: {pin_number}")
      else:
        print("Invalid name,Open an bank Account!")
    # ✅ Change PIN number
    elif choice == 3:
        if pin_number is None:
            print("❌ You must generate a PIN first (Option 2).")
        else:
            new_pin = int(input("Enter your new PIN: "))
            if new_pin != pin_number:
                pin_number = new_pin
                print("✅ PIN successfully changed.")
            else:
                print("⚠️ This is your existing PIN. Try a new one.")

    # ✅ Deposit Amount
    elif choice == 4:
        if pin_number is None:
            print("❌ Generate your PIN first (Option 2).")
        else:
            entered_pin = int(input("Enter your PIN: "))
            if entered_pin == pin_number:
                amount = int(input("Enter the amount to deposit: ₹"))
                balance += amount
                print(f"✅ ₹{amount} deposited successfully.")
            else:
                print("❌ Incorrect PIN.")

    # ✅ Withdraw Amount
    elif choice == 5:
        if pin_number is None:
            print("❌ Generate your PIN first (Option 2).")
        else:
            entered_pin = i3
            nt(input("Enter your PIN: "))
            if entered_pin == pin_number:
                withdraw_amount = int(input("Enter the amount to withdraw: ₹"))
                if withdraw_amount > balance:
                    print("❌ Insufficient Balance.")
                else:
                    balance -= withdraw_amount
                    print(f"✅ ₹{withdraw_amount} withdrawn successfully.")
            else:
                print("❌ Incorrect PIN.")

    # ✅ Check Balance
    elif choice == 6:
        print(f"💰 Your current balance is ₹{balance}")

    # ✅ Exit
    elif choice == 7:
        print("🙏 Thank you for visiting Dhanush's World. Goodbye!")
        break

    # ✅ Invalid Input
    else:
        print("❌ Invalid option. Please select a number between 1 and 7.")